// 指定的当前proto语法的版本，有2和3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//     protoc-gen-go v1.27.1
//     protoc        v3.19.1
// source: csr.proto

// 指定等会文件生成出来的package

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
//ObjectType string        `json:"docType"`   // 消息类型
//MsgId      string        `json:"msg_id"`    // 信息 id
//Sender     string        `json:"sender"`    // 发送者
//Recipient  string        `json:"recipient"` // 接受者
//Body       string        `json:"body"`      // 消息体
//DataHash   string        `json:"hash"`      // 整体数据 hash
//TimeDate   string        `json:"time_date"` // 日期
type SaveMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectType string `protobuf:"bytes,1,opt,name=objectType,proto3" json:"objectType,omitempty"`
	Sender     string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient  string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Body       string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	DataHash   string `protobuf:"bytes,5,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
	TimeDate   string `protobuf:"bytes,6,opt,name=timeDate,proto3" json:"timeDate,omitempty"`
}

func (x *SaveMsgRequest) Reset() {
	*x = SaveMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMsgRequest) ProtoMessage() {}

func (x *SaveMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMsgRequest.ProtoReflect.Descriptor instead.
func (*SaveMsgRequest) Descriptor() ([]byte, []int) {
	return file_csr_proto_rawDescGZIP(), []int{0}
}

func (x *SaveMsgRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *SaveMsgRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SaveMsgRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SaveMsgRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SaveMsgRequest) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

func (x *SaveMsgRequest) GetTimeDate() string {
	if x != nil {
		return x.TimeDate
	}
	return ""
}

type SaveMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TxId string `protobuf:"bytes,3,opt,name=txId,proto3" json:"txId,omitempty"`
}

func (x *SaveMsgResponse) Reset() {
	*x = SaveMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMsgResponse) ProtoMessage() {}

func (x *SaveMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMsgResponse.ProtoReflect.Descriptor instead.
func (*SaveMsgResponse) Descriptor() ([]byte, []int) {
	return file_csr_proto_rawDescGZIP(), []int{1}
}

func (x *SaveMsgResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SaveMsgResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SaveMsgResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

var File_csr_proto protoreflect.FileDescriptor

var file_csr_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x73, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xb2, 0x01, 0x0a, 0x0e, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x65, 0x22, 0x4b, 0x0a, 0x0f, 0x53, 0x61, 0x76, 0x65, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x78, 0x49, 0x64, 0x32, 0x4b, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x70, 0x63,
	0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_csr_proto_rawDescOnce sync.Once
	file_csr_proto_rawDescData = file_csr_proto_rawDesc
)

func file_csr_proto_rawDescGZIP() []byte {
	file_csr_proto_rawDescOnce.Do(func() {
		file_csr_proto_rawDescData = protoimpl.X.CompressGZIP(file_csr_proto_rawDescData)
	})
	return file_csr_proto_rawDescData
}

var file_csr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_csr_proto_goTypes = []interface{}{
	(*SaveMsgRequest)(nil),  // 0: proto.SaveMsgRequest
	(*SaveMsgResponse)(nil), // 1: proto.SaveMsgResponse
}
var file_csr_proto_depIdxs = []int32{
	0, // 0: proto.MsgService.SaveMsgRpc:input_type -> proto.SaveMsgRequest
	1, // 1: proto.MsgService.SaveMsgRpc:output_type -> proto.SaveMsgResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_csr_proto_init() }
func file_csr_proto_init() {
	if File_csr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_csr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_csr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_csr_proto_goTypes,
		DependencyIndexes: file_csr_proto_depIdxs,
		MessageInfos:      file_csr_proto_msgTypes,
	}.Build()
	File_csr_proto = out.File
	file_csr_proto_rawDesc = nil
	file_csr_proto_goTypes = nil
	file_csr_proto_depIdxs = nil
}
